# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwin.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from qtpy import QtCore, QtGui, QtWidgets


class Ui_ReoMain(object):
    def setupUi(self, ReoMain):
        ReoMain.setObjectName("ReoMain")
        ReoMain.resize(510, 385)
        icon = QtGui.QIcon.fromTheme("accessories-dictionary")
        ReoMain.setWindowIcon(icon)
        ReoMain.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(ReoMain)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchEntry = QtWidgets.QLineEdit(self.centralwidget)
        self.searchEntry.setStyleSheet("")
        self.searchEntry.setClearButtonEnabled(True)
        self.searchEntry.setObjectName("searchEntry")
        self.horizontalLayout.addWidget(self.searchEntry)
        self.searchButton = QtWidgets.QToolButton(self.centralwidget)
        self.searchButton.setStyleSheet("")
        icon = QtGui.QIcon.fromTheme("edit-find")
        self.searchButton.setIcon(icon)
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout.addWidget(self.searchButton)
        self.clearButton = QtWidgets.QToolButton(self.centralwidget)
        self.clearButton.setStyleSheet("")
        icon = QtGui.QIcon.fromTheme("edit-clear")
        self.clearButton.setIcon(icon)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout.addWidget(self.clearButton)
        self.audioButton = QtWidgets.QToolButton(self.centralwidget)
        self.audioButton.setStyleSheet("")
        icon = QtGui.QIcon.fromTheme("audio-speakers-symbolic")
        self.audioButton.setIcon(icon)
        self.audioButton.setObjectName("audioButton")
        self.horizontalLayout.addWidget(self.audioButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.defView = QtWidgets.QTextEdit(self.centralwidget)
        self.defView.setStyleSheet("")
        self.defView.setReadOnly(True)
        self.defView.setObjectName("defView")
        self.verticalLayout.addWidget(self.defView)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        ReoMain.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ReoMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 510, 30))
        self.menubar.setObjectName("menubar")
        self.menuSearch = QtWidgets.QMenu(self.menubar)
        self.menuSearch.setObjectName("menuSearch")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        ReoMain.setMenuBar(self.menubar)
        self.actionPaste_Search = QtWidgets.QAction(ReoMain)
        icon = QtGui.QIcon.fromTheme("edit-paste-symbolic")
        self.actionPaste_Search.setIcon(icon)
        self.actionPaste_Search.setObjectName("actionPaste_Search")
        self.actionSearch_Selected = QtWidgets.QAction(ReoMain)
        icon = QtGui.QIcon.fromTheme("edit-find-symbolic")
        self.actionSearch_Selected.setIcon(icon)
        self.actionSearch_Selected.setObjectName("actionSearch_Selected")
        self.actionSave_Definition = QtWidgets.QAction(ReoMain)
        icon = QtGui.QIcon.fromTheme("document-save-symbolic")
        self.actionSave_Definition.setIcon(icon)
        self.actionSave_Definition.setObjectName("actionSave_Definition")
        self.actionRandom_Word = QtWidgets.QAction(ReoMain)
        icon = QtGui.QIcon.fromTheme("media-playlist-shuffle-symbolic")
        self.actionRandom_Word.setIcon(icon)
        self.actionRandom_Word.setObjectName("actionRandom_Word")
        self.actionAbout = QtWidgets.QAction(ReoMain)
        icon = QtGui.QIcon.fromTheme("help-about-symbolic")
        self.actionAbout.setIcon(icon)
        self.actionAbout.setObjectName("actionAbout")
        self.actionQuit = QtWidgets.QAction(ReoMain)
        icon = QtGui.QIcon.fromTheme("window-close-symbolic")
        self.actionQuit.setIcon(icon)
        self.actionQuit.setObjectName("actionQuit")
        self.menuSearch.addAction(self.actionPaste_Search)
        self.menuSearch.addAction(self.actionSearch_Selected)
        self.menuSearch.addAction(self.actionSave_Definition)
        self.menuSearch.addAction(self.actionRandom_Word)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionQuit)
        self.menubar.addAction(self.menuSearch.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(ReoMain)
        self.searchEntry.returnPressed.connect(self.searchButton.click)
        self.clearButton.clicked.connect(self.defView.clear)
        self.clearButton.clicked.connect(self.searchEntry.clear)
        QtCore.QMetaObject.connectSlotsByName(ReoMain)

    def retranslateUi(self, ReoMain):
        _translate = QtCore.QCoreApplication.translate
        ReoMain.setWindowTitle(_translate("ReoMain", "Reo"))
        self.searchButton.setToolTip(_translate("ReoMain", "Search"))
        self.searchButton.setText(_translate("ReoMain", "Search"))
        self.clearButton.setToolTip(_translate("ReoMain", "Clear"))
        self.clearButton.setText(_translate("ReoMain", "Clear"))
        self.audioButton.setToolTip(_translate("ReoMain", "Audio"))
        self.audioButton.setText(_translate("ReoMain", "Audio"))
        self.menuSearch.setTitle(_translate("ReoMain", "Search"))
        self.menuHelp.setTitle(_translate("ReoMain", "Help"))
        self.actionPaste_Search.setText(
            _translate("ReoMain", "Paste && Search"))
        self.actionPaste_Search.setShortcut(
            _translate("ReoMain", "Ctrl+Shift+V"))
        self.actionSearch_Selected.setText(
            _translate("ReoMain", "Search Selected Text"))
        self.actionSearch_Selected.setShortcut(_translate("ReoMain", "Ctrl+S"))
        self.actionSave_Definition.setText(
            _translate("ReoMain", "Save Definition"))
        self.actionSave_Definition.setShortcut(
            _translate("ReoMain", "Ctrl+Shift+S"))
        self.actionRandom_Word.setText(_translate("ReoMain", "Random Word"))
        self.actionRandom_Word.setShortcut(_translate("ReoMain", "Ctrl+R"))
        self.actionAbout.setText(_translate("ReoMain", "About Reo"))
        self.actionQuit.setText(_translate("ReoMain", "Quit"))
